sudo: false
language: python
python:
    - "3.5"

#branches:
#    only:
#        - master
#        - develop

install:
    - pip install -r source/backend/requirements.txt
    
before_script:
    - export FLASK_APP="$TRAVIS_BUILD_DIR/autoapp.py"
    - export FLASK_DEBUG=1

script:
    - flask test
    
after_failure:
    echo "Broken."

after_script:
    echo "Cleanup."